project:
  type: manuscript

manuscript:
  article: EPDS_1A_2C25_Trabajo_de_simulación_III.ipynb

execute:
  enabled: true
  freeze: false
  echo: true
  warning: false
  message: false

format:
  pdf:
    pdf-engine: pdflatex
    documentclass: article
    papersize: a4
    fontsize: 11pt
    lang: en
    title: ""
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    number-sections: true
    number-depth: 3
    toc: true
    toc-depth: 3
    toc-title: "Índice de Contenidos"
    lof: false
    lot: false
    fig-pos: 'H'
    highlight-style: github
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    keep-tex: false
    code-link: false
    include-in-header:
      text: |
        \usepackage[utf8]{inputenc}
        \usepackage[T1]{fontenc}
        \usepackage{fancyhdr}
        \setlength{\headheight}{14pt}
        \addtolength{\topmargin}{-2pt}
        \pagestyle{fancy}
        \fancyhead[L]{Trabajo de Simulación III}
        \fancyhead[R]{IFTS N° 29}
        \usepackage{float}
        \floatplacement{figure}{H}
        \usepackage{graphicx}
    include-before-body:
      text: |
        \begin{titlepage}
        \centering
        % LOGO DE LA INSTITUCIÓN
        \includegraphics[width=0.3\textwidth]{logo.png}\\[2cm]
        
        % TÍTULO DEL TRABAJO
        {\Huge\bfseries Trabajo de Simulación III\par}
        \vspace{1cm}
        
        % INSTITUCIÓN
        {\Large Instituto de Formación Técnica Superior N° 29\par}
        \vspace{0.5cm}
        
        % ASIGNATURA
        {\large Estadística y Probabilidad para el Desarrollo de Software\par}
        \vspace{2cm}
        
        % AUTORES
        {\large
        Rinaldi, Flavio\\
        Sabato, Ángel\\
        Shifman, Iván\\
        Zárate, Marcelo\\
        \par}
        
        \vfill

        \end{titlepage}
    link-citations: true
    colorlinks: true
    urlcolor: blue
    linkcolor: black
    citecolor: blue

fig-cap-location: bottom
fig-dpi: 300
fig-format: png
fig-width: 10
fig-height: 6
fig-align: center

tbl-cap-location: top

code-annotations: hover
code-overflow: wrap
code-fold: false

jupyter: python3

notebook-links: false
notebook-view: false